(module rnumber
  (extern
   ;; beginning of cl-bl-rnumber.h
  ;;   (rnumber-create::RNumber_proxy_t () "bl_rnumber_create")
   (include "C-RNumber.h")
   (rnumber-create::s-RNumber* () "bl_rnumber_create")
   (rnumber-create-from-unsigned::s-RNumber* (uint) "bl_rnumber_create_from_unsigned")
   (rnumber-create-from-unsigned_variable_sizing::RNumber_proxy_t (uint) "bl_rnumber_create_from_unsigned_variable_sizing")
   (rnumber-create-from-unsigned_of_size::RNumber_proxy_t (uint uint) "bl_rnumber_create_from_unsigned_of_size")
   (rnumber-create-from-unsigned_of_size_variable_sizing::RNumber_proxy_t (uint uint) "bl_rnumber_create_from_unsigned_of_size_variable_sizing")
   (rnumber-create-from-string::RNumber_proxy_t (string) "bl_rnumber_create_from_string")
   (rnumber-create-from-string-variable-sizing::RNumber_proxy_t (string) "bl_rnumber_create_from_string_variable_sizing")
   (rnumber-create-from-string-of-size::RNumber_proxy_t (string uint) "bl_rnumber_create_from_string_of_size")
   (rnumber-create-from-string-of-size_variable_sizing::RNumber_proxy_t (string uint) "bl_rnumber_create_from_string_of_size_variable_sizing")
   (rnumber-create-from-string-of-radix::RNumber_proxy_t (string int) "bl_rnumber_create_from_string_of_radix")
   (rnumber-create-from-string-of-radix_variable_sizing::RNumber_proxy_t (string int) "bl_rnumber_create_from_string_of_radix_variable_sizing")
   (rnumber-create-from-string-of-size-of-radix::RNumber_proxy_t (string uint int) "bl_rnumber_create_from_string_of_size_of_radix")
   (rnumber-create-from-string-of-size-of-radix-variable-sizing::RNumber_proxy_t (string uint int) "bl_rnumber_create_from_string_of_size_of_radix_variable_sizing")
   (rnumber-create-from-numVector::RNumber_proxy_t (uint* uint uint) "bl_rnumber_create_from_numVector")
   (rnumber-create-from-numVector-variable-sizing::RNumber_proxy_t (uint* uint uint) "bl_rnumber_create_from_numVector_variable_sizing")
   (rnumber-create-from-rnumber::RNumber_proxy_t (s-RNumber*) "bl_rnumber_create_from_rnumber")
   (rnumber-copy-to-size::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_copy_to_size")
   (rnumber-copy-to-size-variable-sizing::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_copy_to_size_variable_sizing")
   (rnumber-unary-minus::RNumber_proxy_t (s-RNumber*) "bl_rnumber_unary_minus")
   (rnumber-unary-tilde::RNumber_proxy_t (s-RNumber*) "bl_rnumber_unary_tilde")
   (rnumber-getfield::RNumber_proxy_t (s-RNumber* uint uint) "bl_rnumber_getfield")
   (rnumber-rn-plus-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_plus_rn")
   (rnumber-rn-plus-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_plus_ui")
   (rnumber-ui-plus-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_plus_rn")
   (rnumber-rn-add-ext_rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_add_ext_rn")
   (rnumber-rn-add-ext_ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_add_ext_ui")
   (rnumber-ui-add-ext_rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_add_ext_rn")
   (rnumber-rn-minus-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_minus_rn")
   (rnumber-rn-minus-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_minus_ui")
   (rnumber-ui-minus-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_minus_rn")
   (rnumber-rn-multiply-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_multiply_rn")
   (rnumber-rn-multiply-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_multiply_ui")
   (rnumber-ui-multiply-ui::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_multiply_ui")
   (rnumber-rn-multiply-ext_rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_multiply_ext_rn")
   (rnumber-rn-multiply-ext_ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_multiply_ext_ui")
   (rnumber-ui-multiply-ext_rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_multiply_ext_rn")
   (rnumber-rn-divide-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_divide_rn")
   (rnumber-rn-divide-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_divide_ui")
   (rnumber-ui-divide-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_divide_rn")
   (rnumber-rn-mod-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_mod_rn")
   (rnumber-rn-mod-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_mod_ui")
   (rnumber-ui-mod-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_mod_rn")
   (rnumber-rn-bitand-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_bitand_rn")
   (rnumber-rn-bitand-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_bitand_ui")
   (rnumber-ui-bitand-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_bitand_rn")
   (rnumber-rn-bitor-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_bitor_rn")
   (rnumber-rn-bitor-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_bitor_ui")
   (rnumber-ui-bitor-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_bitor_rn")
   (rnumber-rn-bitxor-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_bitxor_rn")
   (rnumber-rn-bitxor-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_bitxor_ui")
   (rnumber-ui-bitxor-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_bitxor_rn")
   (rnumber-rn-leftshift-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_leftshift_rn")
   (rnumber-rn-leftshift-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_leftshift_ui")
   (rnumber-ui-leftshift-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_leftshift_rn")
   (rnumber-rn-leftshift-ext-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_leftshift_ext_rn")
   (rnumber-rn-leftshift-ext-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_leftshift_ext_ui")
   (rnumber-ui-leftshift-ext-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_leftshift_ext_rn")
   (rnumber-rn-rightshift-rn::RNumber_proxy_t (s-RNumber* s-RNumber*) "bl_rnumber_rn_rightshift_rn")
   (rnumber-rn-rightshift-ui::RNumber_proxy_t (s-RNumber* uint) "bl_rnumber_rn_rightshift_ui")
   (rnumber-ui-rightshift-rn::RNumber_proxy_t (uint s-RNumber*) "bl_rnumber_ui_rightshift_rn")
   (type s-RNumber (struct) "struct RNumber")
   (type s-RNumber_proxy (struct) "struct RNumber_proxy")
   (type RNumber_proxy_t s-RNumber_proxy* "RNumber_proxy_t")
   (type ->RNumber_proxy_t "RNumber_proxy_t ($())")
   (type uint->RNumber_proxy_t "RNumber_proxy_t ($(unsigned int))")
   (type uint,uint->RNumber_proxy_t "RNumber_proxy_t ($(unsigned int,unsigned int))")
   (type string->RNumber_proxy_t "RNumber_proxy_t ($(char *))")
   (type string,uint->RNumber_proxy_t "RNumber_proxy_t ($(char *,unsigned int))")
   (type string,int->RNumber_proxy_t "RNumber_proxy_t ($(char *,int))")
   (type string,uint,int->RNumber_proxy_t "RNumber_proxy_t ($(char *,unsigned int,int))")
   (type uint*,uint,uint->RNumber_proxy_t "RNumber_proxy_t ($(unsigned int *,unsigned int,unsigned int))")
   (type s-RNumber*->RNumber_proxy_t "RNumber_proxy_t ($(struct RNumber *))")
   (type s-RNumber*,uint->RNumber_proxy_t "RNumber_proxy_t ($(struct RNumber *,unsigned int))")
   (type s-RNumber*,uint,uint->RNumber_proxy_t "RNumber_proxy_t ($(struct RNumber *,unsigned int,unsigned int))")
   (type s-RNumber*,s-RNumber*->RNumber_proxy_t "RNumber_proxy_t ($(struct RNumber *,struct RNumber *))")
   (type uint,s-RNumber*->RNumber_proxy_t "RNumber_proxy_t ($(unsigned int,struct RNumber *))")
   ;; end of cl-bl-rnumber.h
   ;; beginning of cl-C-RNumber.h
   (rnumber-destroy::void (s-RNumber*) "rnumber_destroy")
   (rnumber-assign_from_uint::s-RNumber* (s-RNumber* uint) "rnumber_assign_from_uint")
   (rnumber-assign_from_string::s-RNumber* (s-RNumber* string) "rnumber_assign_from_string")
   (rnumber-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_assign")
   (rnumber-copy::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_copy")
   (rnumber-resize::void (s-RNumber* uint) "rnumber_resize")
   (rnumber-plus-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_plus_assign")
   (rnumber-plus-assign_from_unsigned::s-RNumber* (s-RNumber* uint) "rnumber_plus_assign_from_unsigned")
   (rnumber-minus-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_minus_assign")
   (rnumber-minus-assign_from_unsigned::s-RNumber* (s-RNumber* uint) "rnumber_minus_assign_from_unsigned")
   (rnumber-multiply-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_multiply_assign")
   (rnumber-multiply-assign_from_unsigned::s-RNumber* (s-RNumber* uint) "rnumber_multiply_assign_from_unsigned")
   (rnumber-divide-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_divide_assign")
   (rnumber-divide-assign-from-unsigned::s-RNumber* (s-RNumber* uint) "rnumber_divide_assign_from_unsigned")
   (rnumber-mod-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_mod_assign")
   (rnumber-mod-assign-from-unsigned::s-RNumber* (s-RNumber* uint) "rnumber_mod_assign_from_unsigned")
   (rnumber-bitand-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_bitand_assign")
   (rnumber-bitand-assign_from_unsigned::s-RNumber* (s-RNumber* uint) "rnumber_bitand_assign_from_unsigned")
   (rnumber-bitor-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_bitor_assign")
   (rnumber-bitor-assign_from_unsigned::s-RNumber* (s-RNumber* uint) "rnumber_bitor_assign_from_unsigned")
   (rnumber-bitxor-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_bitxor_assign")
   (rnumber-bitxor-assign-from-unsigned::s-RNumber* (s-RNumber* uint) "rnumber_bitxor_assign_from_unsigned")
   (rnumber-leftshift-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_leftshift_assign")
   (rnumber-leftshift-assign-from-unsigned::s-RNumber* (s-RNumber* uint) "rnumber_leftshift_assign_from_unsigned")
   (rnumber-rightshift-assign::s-RNumber* (s-RNumber* s-RNumber*) "rnumber_rightshift_assign")
   (rnumber-rightshift-assign_from_unsigned::s-RNumber* (s-RNumber* uint) "rnumber_rightshift_assign_from_unsigned")
   (rnumber-not::int (s-RNumber*) "rnumber_not")
   (rnumber-signed-lessthan::int (s-RNumber* s-RNumber*) "rnumber_signed_lessthan")
   (rnumber-signed-lessequal::int (s-RNumber* s-RNumber*) "rnumber_signed_lessequal")
   (rnumber-signed-greaterthan::int (s-RNumber* s-RNumber*) "rnumber_signed_greaterthan")
   (rnumber-signed-greaterequal::int (s-RNumber* s-RNumber*) "rnumber_signed_greaterequal")
   (rnumber-compare::int (s-RNumber* s-RNumber*) "rnumber_compare")
   (rnumber-invert::s-RNumber* (s-RNumber*) "rnumber_invert")
   (rnumber-negate::s-RNumber* (s-RNumber*) "rnumber_negate")
   (rnumber-set-all::s-RNumber* (s-RNumber*) "rnumber_set_all")
   (rnumber-clear-all::s-RNumber* (s-RNumber*) "rnumber_clear_all")
   (rnumber-sign-extend::s-RNumber* (s-RNumber* uint) "rnumber_sign_extend")
   (rnumber-truncate::s-RNumber* (s-RNumber* uint) "rnumber_truncate")
   (rnumber-getbit::uint (s-RNumber* uint) "rnumber_getbit")
   (rnumber-getbit-lsb::uint (s-RNumber* uint) "rnumber_getbit_lsb")
   (rnumber-setbit::void (s-RNumber* uint uint) "rnumber_setbit")
   (rnumber-setbit-lsb::void (s-RNumber* uint uint) "rnumber_setbit_lsb")
   (rnumber-assignbit::void (s-RNumber* uint uint) "rnumber_assignbit")
   (rnumber-assignbit-lsb::void (s-RNumber* uint uint) "rnumber_assignbit_lsb")
   (rnumber-get_uint::uint (s-RNumber*) "rnumber_get_uint")
   (rnumber-cstr::string (s-RNumber*) "rnumber_cstr")
   (rnumber-cstr-radix::string (s-RNumber* int int) "rnumber_cstr_radix")
   (rnumber-get-int-field::int (s-RNumber* uint uint) "rnumber_get_int_field")
   (rnumber-get-uint-field::uint (s-RNumber* uint uint) "rnumber_get_uint_field")
   (rnumber-set-field::void (s-RNumber* uint uint s-RNumber*) "rnumber_set_field")
   (rnumber-size::uint (s-RNumber*) "rnumber_size")
   (rnumber-wordcount::uint (s-RNumber*) "rnumber_wordcount")
   (rnumber-buffer::uint* (s-RNumber*) "rnumber_buffer")
   (rnumber-get-default_size::uint () "rnumber_get_default_size")
   (rnumber-set-default_size::void (uint) "rnumber_set_default_size")
   (rnumber-sizing::int (s-RNumber*) "rnumber_sizing")
   (rnumber-dynamic::int () "rnumber_dynamic")
   (rnumber-fixed::int () "rnumber_fixed")
   (rnumber-set-dynamic::void (s-RNumber*) "rnumber_set_dynamic")
   (rnumber-set-fixed::void (s-RNumber*) "rnumber_set_fixed")
   (rnumber-print-to-os::void (s-RNumber* void*) "rnumber_print_to_os")
   (rnumber-print-with-radix::void (s-RNumber* void* int int) "rnumber_print_with_radix")
   (rnumber-read_from-is::void (s-RNumber* void*) "rnumber_read_from_is")
   (rnumber-write-to-os::void (s-RNumber* void*) "rnumber_write_to_os")
   (rnumber-rn-notequal-rn::int (s-RNumber* s-RNumber*) "rnumber_rn_notequal_rn")
   (rnumber-rn-notequal-ui::int (s-RNumber* uint) "rnumber_rn_notequal_ui")
   (rnumber-ui-notequal-rn::int (uint s-RNumber*) "rnumber_ui_notequal_rn")
   (rnumber-rn-equal-rn::int (s-RNumber* s-RNumber*) "rnumber_rn_equal_rn")
   (rnumber-rn-equal-ui::int (s-RNumber* uint) "rnumber_rn_equal_ui")
   (rnumber-ui-equal-rn::int (uint s-RNumber*) "rnumber_ui_equal_rn")
   (rnumber-rn-lessthan-rn::int (s-RNumber* s-RNumber*) "rnumber_rn_lessthan_rn")
   (rnumber-rn-lessthan-ui::int (s-RNumber* uint) "rnumber_rn_lessthan_ui")
   (rnumber-ui-lessthan-rn::int (uint s-RNumber*) "rnumber_ui_lessthan_rn")
   (rnumber-rn-lessequal-rn::int (s-RNumber* s-RNumber*) "rnumber_rn_lessequal_rn")
   (rnumber-rn-lessequal-ui::int (s-RNumber* uint) "rnumber_rn_lessequal_ui")
   (rnumber-ui-lessequal-rn::int (uint s-RNumber*) "rnumber_ui_lessequal_rn")
   (rnumber-rn-greaterthan-rn::int (s-RNumber* s-RNumber*) "rnumber_rn_greaterthan_rn")
   (rnumber-rn-greaterthan-ui::int (s-RNumber* uint) "rnumber_rn_greaterthan_ui")
   (rnumber-ui-greaterthan-rn::int (uint s-RNumber*) "rnumber_ui_greaterthan_rn")
   (rnumber-rn-greaterequal-rn::int (s-RNumber* s-RNumber*) "rnumber_rn_greaterequal_rn")
   (rnumber-rn-greaterequal-ui::int (s-RNumber* uint) "rnumber_rn_greaterequal_ui")
   (rnumber-ui-greaterequal-rn::int (uint s-RNumber*) "rnumber_ui_greaterequal_rn")
   (rnumber-rhex::int () "rnumber_rhex")
   (rnumber-rbin::int () "rnumber_rbin")
   (rnumber-rdec::int () "rnumber_rdec")
   (type ->s-RNumber* "struct RNumber *($())")
   (type uint->s-RNumber* "struct RNumber *($(unsigned int))")
   (type uint,uint->s-RNumber* "struct RNumber *($(unsigned int,unsigned int))")
   (type string->s-RNumber* "struct RNumber *($(char *))")
   (type string,uint->s-RNumber* "struct RNumber *($(char *,unsigned int))")
   (type string,int->s-RNumber* "struct RNumber *($(char *,int))")
   (type string,uint,int->s-RNumber* "struct RNumber *($(char *,unsigned int,int))")
   (type uint*,uint,uint->s-RNumber* "struct RNumber *($(unsigned int *,unsigned int,unsigned int))")
   (type s-RNumber*->s-RNumber* "struct RNumber *($(struct RNumber *))")
   (type s-RNumber*,uint->s-RNumber* "struct RNumber *($(struct RNumber *,unsigned int))")
   (type s-RNumber*->void "void ($(struct RNumber *))")
   (type s-RNumber*,string->s-RNumber* "struct RNumber *($(struct RNumber *,char *))")
   (type s-RNumber*,s-RNumber*->s-RNumber* "struct RNumber *($(struct RNumber *,struct RNumber *))")
   (type s-RNumber*,uint->void "void ($(struct RNumber *,unsigned int))")
   (type s-RNumber*->int "int ($(struct RNumber *))")
   (type s-RNumber*,s-RNumber*->int "int ($(struct RNumber *,struct RNumber *))")
   (type s-RNumber*,uint->uint "unsigned int ($(struct RNumber *,unsigned int))")
   (type s-RNumber*,uint,uint->void "void ($(struct RNumber *,unsigned int,unsigned int))")
   (type s-RNumber*->uint "unsigned int ($(struct RNumber *))")
   (type s-RNumber*->string "char *($(struct RNumber *))")
   (type s-RNumber*,int,int->string "char *($(struct RNumber *,int,int))")
   (type s-RNumber*,uint,uint->int "int ($(struct RNumber *,unsigned int,unsigned int))")
   (type s-RNumber*,uint,uint->uint "unsigned int ($(struct RNumber *,unsigned int,unsigned int))")
   (type s-RNumber*,uint,uint->s-RNumber* "struct RNumber *($(struct RNumber *,unsigned int,unsigned int))")
   (type s-RNumber*,uint,uint,s-RNumber*->void "void ($(struct RNumber *,unsigned int,unsigned int,struct RNumber *))")
   (type s-RNumber*->uint* "unsigned int *($(struct RNumber *))")
   (type uint* (pointer uint) "unsigned int *")
   (type ->uint "unsigned int ($())")
   (type uint->void "void ($(unsigned int))")
   (type ->int "int ($())")
   (type s-RNumber*,void*->void "void ($(struct RNumber *,void *))")
   (type s-RNumber*,void*,int,int->void "void ($(struct RNumber *,void *,int,int))")
   (type uint,s-RNumber*->s-RNumber* "struct RNumber *($(unsigned int,struct RNumber *))")
   (type s-RNumber*,uint->int "int ($(struct RNumber *,unsigned int))")
   (type uint,s-RNumber*->int "int ($(unsigned int,struct RNumber *))")
   ;; end of cl-C-RNumber.h
   ;; beginning of C-Random.h
   (random-create::void () "random_create")
   (random-set_gate_all::void (int) "random_set_gate_all")
   (random-set_gate::void (int int) "random_set_gate")
   (random-init::uint () "random_init")
   (random-init_from_seed::uint (uint) "random_init_from_seed")
   (random-add_new_gen::int () "random_add_new_gen")
   (random-add_new_gen_with_seed::int (uint) "random_add_new_gen_with_seed")
   (random-pop_gen::void (int) "random_pop_gen")
   (random-set_cur_gen::int (int) "random_set_cur_gen")
   (random-get_cur_gen::int () "random_get_cur_gen")
   (random-get_num_gen::int () "random_get_num_gen")
   (random-get_rnumber::s-RNumber* (int) "random_get_rnumber")
   (random-get_integer::uint () "random_get_integer")
   (random-get_integer_n::uint (uint) "random_get_integer_n")
   (random-get_double::double () "random_get_double")
   (random-get_from_range_rnumber::s-RNumber* (s-RNumber* s-RNumber*) "random_get_from_range_rnumber")
   (random-get_from_range_unsigned::uint (uint uint) "random_get_from_range_unsigned")
   (random-save::void (void*) "random_save")
   (random-load::void (void*) "random_load")
   (random-get_state::void* () "random_get_state")
   (random-set_state::void (void*) "random_set_state")
   (random-get_count::uint () "random_get_count")
   (type ->void "void ($())")
   (type int->void "void ($(int))")
   (type int,int->void "void ($(int,int))")
   (type uint->uint "unsigned ($(unsigned))")
   (type uint->int "int ($(unsigned))")
   (type int->int "int ($(int))")
   (type int->s-RNumber* "struct RNumber *($(int))")
   (type ->double "double ($())")
   (type uint,uint->uint "unsigned ($(unsigned,unsigned))")
   (type void*->void "void ($(void *))")
   (type ->void* "void *($())")
   ;; end of C-Random.h
   ))
