#!/local/tdukes/bin/perl -- -*-perl-*-a
#
# Simple regression test for RValue iteration
#

$test = "./NumberTest";
$prog = "/usr/bin/dc";

# Run the program
if (system("$test -dc $prog")) {
  print "Error executing test program $test\n";
  exit 1;
}

print "Number test PASSED.\n";

