#!/usr/bin/env perl
#
# Simple regression for testing RNumber's ability to
# read from a stream. 
#

$srcdir = ".";
if (exists $ENV{srcdir}) {
  $srcdir = $ENV{srcdir};
}

$test = "./ReadTest";
$in = "${srcdir}/ReadIn.txt";
$out  = "ReadOut.txt";
$regress = "${srcdir}/ReadOut.regress";
$diff = "diff -bi ";

my $cmd = "$test -xf $in > $out";

# Run the program
if (system($cmd)) {
  print "Error executing '$cmd'.\n";
  exit 1;
}

$output = `$diff $out $regress`;
if ($? > 8) {
  print "Error!  File '$out' differs from regression file '$regress'.\n";
  print "Output was:\n",$output;
  exit 1;
} else {
  print "Regex regression test PASSED.\n";
}

unlink $out;
exit 0;



